apiVersion: v1
kind: Service
metadata:
  name: helloworld
  labels:
    app: helloworld
  namespace: default
spec:
  type: ClusterIP
  ports:
  - port: 8080
  selector:
    app: helloworld
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: helloworld
  labels:
    app: helloworld
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      securityContext:
        runAsUser: 1000
      # TODO: remove once the clusters have worker nodes
      nodeSelector:
        kubernetes.io/role: master
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      # TODO end
      containers:
      - name: helloworld
        image: giantswarm/helloworld:latest
        ports:
        - containerPort: 8080
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  labels:
    app: helloworld 
    kubernetes.io/ingress.class: nginx.ingress.kubernetes.io
  name: helloworld
  namespace: default
spec:
  rules:
  - host: helloworld.zwm5s.k8s.gauss.eu-central-1.aws.gigantic.io
    http:
      paths:
      - path: /
        backend:
          serviceName: helloworld
          servicePort: 8080